INSERT INTO TIPO_USUARIO (TIPO) VALUES ('CLIENTE');
INSERT INTO TIPO_USUARIO (TIPO) VALUES ('VENDEDOR');

INSERT INTO TIPO_OBRA (DESCRIPCION) VALUES ('REFORMA');
INSERT INTO TIPO_OBRA (DESCRIPCION) VALUES ('CASA');
INSERT INTO TIPO_OBRA (DESCRIPCION) VALUES ('EDIFICIO');
INSERT INTO TIPO_OBRA (DESCRIPCION) VALUES ('VIAL');

